spring.application.name=products-command
server.port=8081

# Spring Cloud Function configuration
# esta es la function que quiero activa como binding
# esta seria la function que se va a ejecutar cada vez que llegue un mensaje al topic de comandos
spring.cloud.function.definition=handleCommands

# Configuración de Spring Cloud Stream para el binding de entrada
spring.cloud.stream.bindings.handleCommands-in-0.destination=products.commands
spring.cloud.stream.bindings.handleCommands-in-0.contentType=application/json
spring.cloud.stream.bindings.handleCommands-in-0.group=products-command-group

# Configuración de Kafka broker para Spring Cloud Stream
spring.cloud.stream.kafka.binder.brokers=localhost:9092