spring.application.name=products-command
server.port=8081

# Spring Cloud Function configuration
# esta es la function que quiero activa como binding
# esta seria la function que se va a ejecutar cada vez que llegue un mensaje al topic de comandos
spring.cloud.function.definition=handleCommands

# Configuración de Spring Cloud Stream para el binding de entrada
spring.cloud.stream.bindings.handleCommands-in-0.destination=products.commands
spring.cloud.stream.bindings.handleCommands-in-0.contentType=application/json
# Grupo de consumidores, se usa para el group id de kafka
spring.cloud.stream.bindings.handleCommands-in-0.group=products-command
# Al cargar un nuevo consumidor, se va a leer desde el ultimo mensaje que se haya procesado
spring.cloud.stream.kafka.bindings.handleCommands-in-0.consumer.startOffset=latest
# Configuración de Kafka broker para Spring Cloud Stream
spring.cloud.stream.kafka.binder.brokers=localhost:9092


# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/db_spring_kafka
spring.datasource.username=root
spring.datasource.password=sasa1234
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC