CREATE TABLE IF NOT EXISTS meetup (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      title VARCHAR(255) NOT NULL,
    date TIMESTAMP NOT NULL
    );

CREATE TABLE IF NOT EXISTS rsvp (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    meetup_id BIGINT NOT NULL,
                                    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS confirmation (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            meetup_id BIGINT NOT NULL,
                                            email VARCHAR(255) NOT NULL
    );