spring.application.name=hexagonal-demo
server.port=8080


##database config
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
jdbc.datasource-proxy.query.enable-logging=false
jdbc.datasource-proxy.query.logger-name=bookstore.query-logger
jdbc.datasource-proxy.query.log-level=DEBUG
jdbc.datasource-proxy.multiline=false
logging.level.bookstore.query-logger=DEBUG

# configuracion para mantener la base de datos siempre activa
spring.docker.compose.lifecycle-management=start_only