spring:
  application:
    name:
  ai:
    mcp:
      client:
        stdio:
          connections:
            wikipedia-mcp:
              command: uvx
              args:
                - --from
                - wikipedia-mcp-server
                - wikipedia-mcp

blog-agent:
  output-dir: blog-posts
  number-of-keywords: 5

embabel:
  agent:
    platform:
      models:
        openai:
          api-key: ${OPENAI_API_KEY}
    logging:
      personality: starwars
  models:
    default-llm: gpt-4.1-mini
    llms:
      reviewer: gpt-4.1-mini


