<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>The 'Learn Design Patterns' Course: Structural Design Patterns</description>
    <name>ldp-structural-design-patterns</name>

    <groupId>com.baeldung</groupId>
    <artifactId>ldp-structural-design-patterns</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>the-adapter-pattern-start</module>
        <module>the-adapter-pattern-end</module>
        <module>the-decorator-pattern-start</module>
        <module>the-decorator-pattern-end</module>
        <module>the-proxy-pattern-start</module>
        <module>the-proxy-pattern-end</module>
        <module>the-facade-pattern-start</module>
        <module>the-facade-pattern-end</module>
    </modules>
</project>
